[project]
name = "advent-of-code-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cvxpy>=1.7.5",
    "ecos>=2.0.14",
    "matplotlib>=3.10.7",
    "scipy>=1.16.3",
    "shapely>=2.1.2",
]
